### ISSUE TITLE
Does not work with QUnit 2.17.0

### ISSUE THREAD

**Issue by boris-petrov** [steveszc/ember-cli-memory-leak-detector#46]
I updated QUnit from 2.16.0 to 2.17.0 and my tests started to freeze. I *think* it's because of `ember-cli-memory-leak-detector` because my tests finish and then it freezes there - where I think memory leaks are detected.

**Comment by steveszc** [comment]
Thanks for reporting. This may be related to https://github.com/steveszc/ember-cli-memory-leak-detector/issues/47
Seems like there are some changes in Qunit that break the fundamental way that this addon runs the leak detection and reports memory leaks. 

I haven't had much time to work on this addon lately, but it will require some effort to get things working again with newer versions of Qunit.

**Comment by steveszc** [comment]
Closing in favor of #49
